### ISSUE TITLE
1-wire_DS18B20.py - how many will it read?

### ISSUE THREAD

**Issue by Sopor** [JoBergs/RaspiContent#2]
I have 10 DS18B20 connected but i will only show one value. So this python script will only read one of my 10 DS18B20?

**Comment by JoBergs** [comment]
This script is for accessing just one sensor automatically. Have a look at this line:
self.sensor_path = glob.glob(base_path + '28*')[0] + file_name 
With [0], i access only the first sensor that is connected.
You would need to modify the script so that all sensors found by glob there are read.
